name: Deploy HTML with GitHub Token

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Replace token in HTML
      run: |
        # Reemplazar el marcador de posición en busqueda.html
        sed -i 's/__GITHUB_TOKEN__/${{ secrets.SECRETO }}/g' busqueda.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SECRETO }}
        publish_dir: ./ # Directorio a publicar en GitHub Pages
