name: Deploy HTML with GitHub Token

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Create token file
      run: |
        echo "{\"githubToken\": \"${{ secrets.SECRETO }}\"}" > token.json
        # Aquí puedes añadir otros pasos para desplegar el HTML o usar un servidor
